/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MyPopRouteImport } from './routes/my-pop'
import { Route as MyPassRouteImport } from './routes/my-pass'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChangeLogRouteImport } from './routes/change-log'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DocsUsersRouteImport } from './routes/docs.users'
import { Route as DocsAdminRouteImport } from './routes/docs.admin'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated.scan'
import { Route as AuthenticatedRecoverWalletRouteImport } from './routes/_authenticated.recover-wallet'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as EventsSlugRsvpRouteImport } from './routes/events.$slug.rsvp'
import { Route as AuthenticatedScanSuccessRouteImport } from './routes/_authenticated.scan.success'
import { Route as AuthenticatedAdminWalletsRouteImport } from './routes/_authenticated.admin.wallets'
import { Route as AuthenticatedAdminSignupsRouteImport } from './routes/_authenticated.admin.signups'
import { Route as AuthenticatedAdminRewardsRouteImport } from './routes/_authenticated.admin.rewards'
import { Route as AuthenticatedAdminPopAwardsRouteImport } from './routes/_authenticated.admin.pop-awards'
import { Route as AuthenticatedAdminMintTokenRouteImport } from './routes/_authenticated.admin.mint-token'
import { Route as AuthenticatedAdminEmailTemplatesRouteImport } from './routes/_authenticated.admin.email-templates'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated.admin.crm'
import { Route as AuthenticatedAdminCodesRouteImport } from './routes/_authenticated.admin.codes'
import { Route as AuthenticatedAdminBlastRouteImport } from './routes/_authenticated.admin.blast'
import { Route as AuthenticatedAdminEventsIndexRouteImport } from './routes/_authenticated.admin.events.index'
import { Route as AuthenticatedAdminBlastIndexRouteImport } from './routes/_authenticated.admin.blast.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksBlastDrainRouteImport } from './routes/api/public/hooks/blast-drain'
import { Route as AuthenticatedAdminEventsIdRouteImport } from './routes/_authenticated.admin.events.$id'
import { Route as AuthenticatedAdminBlastHistoryRouteImport } from './routes/_authenticated.admin.blast.history'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPopRoute = MyPopRouteImport.update({
  id: '/my-pop',
  path: '/my-pop',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPassRoute = MyPassRouteImport.update({
  id: '/my-pass',
  path: '/my-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeLogRoute = ChangeLogRouteImport.update({
  id: '/change-log',
  path: '/change-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsUsersRoute = DocsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAdminRoute = DocsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DocsRoute,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecoverWalletRoute =
  AuthenticatedRecoverWalletRouteImport.update({
    id: '/recover-wallet',
    path: '/recover-wallet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRsvpRoute = EventsSlugRsvpRouteImport.update({
  id: '/events/$slug/rsvp',
  path: '/events/$slug/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScanSuccessRoute =
  AuthenticatedScanSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AuthenticatedScanRoute,
  } as any)
const AuthenticatedAdminWalletsRoute =
  AuthenticatedAdminWalletsRouteImport.update({
    id: '/wallets',
    path: '/wallets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSignupsRoute =
  AuthenticatedAdminSignupsRouteImport.update({
    id: '/signups',
    path: '/signups',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRewardsRoute =
  AuthenticatedAdminRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPopAwardsRoute =
  AuthenticatedAdminPopAwardsRouteImport.update({
    id: '/pop-awards',
    path: '/pop-awards',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMintTokenRoute =
  AuthenticatedAdminMintTokenRouteImport.update({
    id: '/mint-token',
    path: '/mint-token',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailTemplatesRoute =
  AuthenticatedAdminEmailTemplatesRouteImport.update({
    id: '/email-templates',
    path: '/email-templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCodesRoute = AuthenticatedAdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBlastRoute = AuthenticatedAdminBlastRouteImport.update({
  id: '/blast',
  path: '/blast',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEventsIndexRoute =
  AuthenticatedAdminEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlastIndexRoute =
  AuthenticatedAdminBlastIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminBlastRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBlastDrainRoute =
  ApiPublicHooksBlastDrainRouteImport.update({
    id: '/public/hooks/blast-drain',
    path: '/public/hooks/blast-drain',
    getParentRoute: () => ApiRoute,
  } as any)
const AuthenticatedAdminEventsIdRoute =
  AuthenticatedAdminEventsIdRouteImport.update({
    id: '/events/$id',
    path: '/events/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlastHistoryRoute =
  AuthenticatedAdminBlastHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedAdminBlastRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/change-log': typeof ChangeLogRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/mission': typeof MissionRoute
  '/my-pass': typeof MyPassRoute
  '/my-pop': typeof MyPopRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/recover-wallet': typeof AuthenticatedRecoverWalletRoute
  '/scan': typeof AuthenticatedScanRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/docs/admin': typeof DocsAdminRoute
  '/docs/users': typeof DocsUsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/docs/': typeof DocsIndexRoute
  '/admin/blast': typeof AuthenticatedAdminBlastRouteWithChildren
  '/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/email-templates': typeof AuthenticatedAdminEmailTemplatesRoute
  '/admin/mint-token': typeof AuthenticatedAdminMintTokenRoute
  '/admin/pop-awards': typeof AuthenticatedAdminPopAwardsRoute
  '/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/admin/signups': typeof AuthenticatedAdminSignupsRoute
  '/admin/wallets': typeof AuthenticatedAdminWalletsRoute
  '/scan/success': typeof AuthenticatedScanSuccessRoute
  '/events/$slug/rsvp': typeof EventsSlugRsvpRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/blast/history': typeof AuthenticatedAdminBlastHistoryRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/api/public/hooks/blast-drain': typeof ApiPublicHooksBlastDrainRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/blast/': typeof AuthenticatedAdminBlastIndexRoute
  '/admin/events/': typeof AuthenticatedAdminEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/change-log': typeof ChangeLogRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/mission': typeof MissionRoute
  '/my-pass': typeof MyPassRoute
  '/my-pop': typeof MyPopRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app': typeof AuthenticatedAppRoute
  '/recover-wallet': typeof AuthenticatedRecoverWalletRoute
  '/scan': typeof AuthenticatedScanRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/docs/admin': typeof DocsAdminRoute
  '/docs/users': typeof DocsUsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/docs': typeof DocsIndexRoute
  '/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/email-templates': typeof AuthenticatedAdminEmailTemplatesRoute
  '/admin/mint-token': typeof AuthenticatedAdminMintTokenRoute
  '/admin/pop-awards': typeof AuthenticatedAdminPopAwardsRoute
  '/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/admin/signups': typeof AuthenticatedAdminSignupsRoute
  '/admin/wallets': typeof AuthenticatedAdminWalletsRoute
  '/scan/success': typeof AuthenticatedScanSuccessRoute
  '/events/$slug/rsvp': typeof EventsSlugRsvpRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/blast/history': typeof AuthenticatedAdminBlastHistoryRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/api/public/hooks/blast-drain': typeof ApiPublicHooksBlastDrainRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/blast': typeof AuthenticatedAdminBlastIndexRoute
  '/admin/events': typeof AuthenticatedAdminEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/api': typeof ApiRouteWithChildren
  '/change-log': typeof ChangeLogRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/mission': typeof MissionRoute
  '/my-pass': typeof MyPassRoute
  '/my-pop': typeof MyPopRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/recover-wallet': typeof AuthenticatedRecoverWalletRoute
  '/_authenticated/scan': typeof AuthenticatedScanRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/docs/admin': typeof DocsAdminRoute
  '/docs/users': typeof DocsUsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/docs/': typeof DocsIndexRoute
  '/_authenticated/admin/blast': typeof AuthenticatedAdminBlastRouteWithChildren
  '/_authenticated/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/_authenticated/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/_authenticated/admin/email-templates': typeof AuthenticatedAdminEmailTemplatesRoute
  '/_authenticated/admin/mint-token': typeof AuthenticatedAdminMintTokenRoute
  '/_authenticated/admin/pop-awards': typeof AuthenticatedAdminPopAwardsRoute
  '/_authenticated/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/_authenticated/admin/signups': typeof AuthenticatedAdminSignupsRoute
  '/_authenticated/admin/wallets': typeof AuthenticatedAdminWalletsRoute
  '/_authenticated/scan/success': typeof AuthenticatedScanSuccessRoute
  '/events/$slug/rsvp': typeof EventsSlugRsvpRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/blast/history': typeof AuthenticatedAdminBlastHistoryRoute
  '/_authenticated/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/api/public/hooks/blast-drain': typeof ApiPublicHooksBlastDrainRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/admin/blast/': typeof AuthenticatedAdminBlastIndexRoute
  '/_authenticated/admin/events/': typeof AuthenticatedAdminEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/change-log'
    | '/docs'
    | '/login'
    | '/logout'
    | '/mission'
    | '/my-pass'
    | '/my-pop'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/admin'
    | '/app'
    | '/recover-wallet'
    | '/scan'
    | '/auth/callback'
    | '/claim/$token'
    | '/docs/admin'
    | '/docs/users'
    | '/email/unsubscribe'
    | '/docs/'
    | '/admin/blast'
    | '/admin/codes'
    | '/admin/crm'
    | '/admin/email-templates'
    | '/admin/mint-token'
    | '/admin/pop-awards'
    | '/admin/rewards'
    | '/admin/signups'
    | '/admin/wallets'
    | '/scan/success'
    | '/events/$slug/rsvp'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/admin/blast/history'
    | '/admin/events/$id'
    | '/api/public/hooks/blast-drain'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/blast/'
    | '/admin/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/change-log'
    | '/login'
    | '/logout'
    | '/mission'
    | '/my-pass'
    | '/my-pop'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/app'
    | '/recover-wallet'
    | '/scan'
    | '/auth/callback'
    | '/claim/$token'
    | '/docs/admin'
    | '/docs/users'
    | '/email/unsubscribe'
    | '/docs'
    | '/admin/codes'
    | '/admin/crm'
    | '/admin/email-templates'
    | '/admin/mint-token'
    | '/admin/pop-awards'
    | '/admin/rewards'
    | '/admin/signups'
    | '/admin/wallets'
    | '/scan/success'
    | '/events/$slug/rsvp'
    | '/lovable/email/suppression'
    | '/admin'
    | '/admin/blast/history'
    | '/admin/events/$id'
    | '/api/public/hooks/blast-drain'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/blast'
    | '/admin/events'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/api'
    | '/change-log'
    | '/docs'
    | '/login'
    | '/logout'
    | '/mission'
    | '/my-pass'
    | '/my-pop'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/recover-wallet'
    | '/_authenticated/scan'
    | '/auth/callback'
    | '/claim/$token'
    | '/docs/admin'
    | '/docs/users'
    | '/email/unsubscribe'
    | '/docs/'
    | '/_authenticated/admin/blast'
    | '/_authenticated/admin/codes'
    | '/_authenticated/admin/crm'
    | '/_authenticated/admin/email-templates'
    | '/_authenticated/admin/mint-token'
    | '/_authenticated/admin/pop-awards'
    | '/_authenticated/admin/rewards'
    | '/_authenticated/admin/signups'
    | '/_authenticated/admin/wallets'
    | '/_authenticated/scan/success'
    | '/events/$slug/rsvp'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/blast/history'
    | '/_authenticated/admin/events/$id'
    | '/api/public/hooks/blast-drain'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/admin/blast/'
    | '/_authenticated/admin/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiRoute: typeof ApiRouteWithChildren
  ChangeLogRoute: typeof ChangeLogRoute
  DocsRoute: typeof DocsRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  MissionRoute: typeof MissionRoute
  MyPassRoute: typeof MyPassRoute
  MyPopRoute: typeof MyPopRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  EventsSlugRsvpRoute: typeof EventsSlugRsvpRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-pop': {
      id: '/my-pop'
      path: '/my-pop'
      fullPath: '/my-pop'
      preLoaderRoute: typeof MyPopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-pass': {
      id: '/my-pass'
      path: '/my-pass'
      fullPath: '/my-pass'
      preLoaderRoute: typeof MyPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-log': {
      id: '/change-log'
      path: '/change-log'
      fullPath: '/change-log'
      preLoaderRoute: typeof ChangeLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/users': {
      id: '/docs/users'
      path: '/users'
      fullPath: '/docs/users'
      preLoaderRoute: typeof DocsUsersRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/admin': {
      id: '/docs/admin'
      path: '/admin'
      fullPath: '/docs/admin'
      preLoaderRoute: typeof DocsAdminRouteImport
      parentRoute: typeof DocsRoute
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recover-wallet': {
      id: '/_authenticated/recover-wallet'
      path: '/recover-wallet'
      fullPath: '/recover-wallet'
      preLoaderRoute: typeof AuthenticatedRecoverWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/rsvp': {
      id: '/events/$slug/rsvp'
      path: '/events/$slug/rsvp'
      fullPath: '/events/$slug/rsvp'
      preLoaderRoute: typeof EventsSlugRsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scan/success': {
      id: '/_authenticated/scan/success'
      path: '/success'
      fullPath: '/scan/success'
      preLoaderRoute: typeof AuthenticatedScanSuccessRouteImport
      parentRoute: typeof AuthenticatedScanRoute
    }
    '/_authenticated/admin/wallets': {
      id: '/_authenticated/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AuthenticatedAdminWalletsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/signups': {
      id: '/_authenticated/admin/signups'
      path: '/signups'
      fullPath: '/admin/signups'
      preLoaderRoute: typeof AuthenticatedAdminSignupsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rewards': {
      id: '/_authenticated/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AuthenticatedAdminRewardsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pop-awards': {
      id: '/_authenticated/admin/pop-awards'
      path: '/pop-awards'
      fullPath: '/admin/pop-awards'
      preLoaderRoute: typeof AuthenticatedAdminPopAwardsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mint-token': {
      id: '/_authenticated/admin/mint-token'
      path: '/mint-token'
      fullPath: '/admin/mint-token'
      preLoaderRoute: typeof AuthenticatedAdminMintTokenRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/email-templates': {
      id: '/_authenticated/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AuthenticatedAdminEmailTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/crm': {
      id: '/_authenticated/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/codes': {
      id: '/_authenticated/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AuthenticatedAdminCodesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blast': {
      id: '/_authenticated/admin/blast'
      path: '/blast'
      fullPath: '/admin/blast'
      preLoaderRoute: typeof AuthenticatedAdminBlastRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events/': {
      id: '/_authenticated/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AuthenticatedAdminEventsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blast/': {
      id: '/_authenticated/admin/blast/'
      path: '/'
      fullPath: '/admin/blast/'
      preLoaderRoute: typeof AuthenticatedAdminBlastIndexRouteImport
      parentRoute: typeof AuthenticatedAdminBlastRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/blast-drain': {
      id: '/api/public/hooks/blast-drain'
      path: '/public/hooks/blast-drain'
      fullPath: '/api/public/hooks/blast-drain'
      preLoaderRoute: typeof ApiPublicHooksBlastDrainRouteImport
      parentRoute: typeof ApiRoute
    }
    '/_authenticated/admin/events/$id': {
      id: '/_authenticated/admin/events/$id'
      path: '/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AuthenticatedAdminEventsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blast/history': {
      id: '/_authenticated/admin/blast/history'
      path: '/history'
      fullPath: '/admin/blast/history'
      preLoaderRoute: typeof AuthenticatedAdminBlastHistoryRouteImport
      parentRoute: typeof AuthenticatedAdminBlastRoute
    }
  }
}

interface AuthenticatedAdminBlastRouteChildren {
  AuthenticatedAdminBlastHistoryRoute: typeof AuthenticatedAdminBlastHistoryRoute
  AuthenticatedAdminBlastIndexRoute: typeof AuthenticatedAdminBlastIndexRoute
}

const AuthenticatedAdminBlastRouteChildren: AuthenticatedAdminBlastRouteChildren =
  {
    AuthenticatedAdminBlastHistoryRoute: AuthenticatedAdminBlastHistoryRoute,
    AuthenticatedAdminBlastIndexRoute: AuthenticatedAdminBlastIndexRoute,
  }

const AuthenticatedAdminBlastRouteWithChildren =
  AuthenticatedAdminBlastRoute._addFileChildren(
    AuthenticatedAdminBlastRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBlastRoute: typeof AuthenticatedAdminBlastRouteWithChildren
  AuthenticatedAdminCodesRoute: typeof AuthenticatedAdminCodesRoute
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRoute
  AuthenticatedAdminEmailTemplatesRoute: typeof AuthenticatedAdminEmailTemplatesRoute
  AuthenticatedAdminMintTokenRoute: typeof AuthenticatedAdminMintTokenRoute
  AuthenticatedAdminPopAwardsRoute: typeof AuthenticatedAdminPopAwardsRoute
  AuthenticatedAdminRewardsRoute: typeof AuthenticatedAdminRewardsRoute
  AuthenticatedAdminSignupsRoute: typeof AuthenticatedAdminSignupsRoute
  AuthenticatedAdminWalletsRoute: typeof AuthenticatedAdminWalletsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEventsIdRoute: typeof AuthenticatedAdminEventsIdRoute
  AuthenticatedAdminEventsIndexRoute: typeof AuthenticatedAdminEventsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBlastRoute: AuthenticatedAdminBlastRouteWithChildren,
  AuthenticatedAdminCodesRoute: AuthenticatedAdminCodesRoute,
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRoute,
  AuthenticatedAdminEmailTemplatesRoute: AuthenticatedAdminEmailTemplatesRoute,
  AuthenticatedAdminMintTokenRoute: AuthenticatedAdminMintTokenRoute,
  AuthenticatedAdminPopAwardsRoute: AuthenticatedAdminPopAwardsRoute,
  AuthenticatedAdminRewardsRoute: AuthenticatedAdminRewardsRoute,
  AuthenticatedAdminSignupsRoute: AuthenticatedAdminSignupsRoute,
  AuthenticatedAdminWalletsRoute: AuthenticatedAdminWalletsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEventsIdRoute: AuthenticatedAdminEventsIdRoute,
  AuthenticatedAdminEventsIndexRoute: AuthenticatedAdminEventsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedScanRouteChildren {
  AuthenticatedScanSuccessRoute: typeof AuthenticatedScanSuccessRoute
}

const AuthenticatedScanRouteChildren: AuthenticatedScanRouteChildren = {
  AuthenticatedScanSuccessRoute: AuthenticatedScanSuccessRoute,
}

const AuthenticatedScanRouteWithChildren =
  AuthenticatedScanRoute._addFileChildren(AuthenticatedScanRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedRecoverWalletRoute: typeof AuthenticatedRecoverWalletRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedRecoverWalletRoute: AuthenticatedRecoverWalletRoute,
  AuthenticatedScanRoute: AuthenticatedScanRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiRouteChildren {
  ApiPublicHooksBlastDrainRoute: typeof ApiPublicHooksBlastDrainRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiPublicHooksBlastDrainRoute: ApiPublicHooksBlastDrainRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

interface DocsRouteChildren {
  DocsAdminRoute: typeof DocsAdminRoute
  DocsUsersRoute: typeof DocsUsersRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAdminRoute: DocsAdminRoute,
  DocsUsersRoute: DocsUsersRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiRoute: ApiRouteWithChildren,
  ChangeLogRoute: ChangeLogRoute,
  DocsRoute: DocsRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  MissionRoute: MissionRoute,
  MyPassRoute: MyPassRoute,
  MyPopRoute: MyPopRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ClaimTokenRoute: ClaimTokenRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  EventsSlugRsvpRoute: EventsSlugRsvpRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
