/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated.scan'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as EventsSlugRsvpRouteImport } from './routes/events.$slug.rsvp'
import { Route as AuthenticatedScanSuccessRouteImport } from './routes/_authenticated.scan.success'
import { Route as AuthenticatedAdminEventsIdRouteImport } from './routes/_authenticated.admin.events.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const EventsSlugRsvpRoute = EventsSlugRsvpRouteImport.update({
  id: '/events/$slug/rsvp',
  path: '/events/$slug/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScanSuccessRoute =
  AuthenticatedScanSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AuthenticatedScanRoute,
  } as any)
const AuthenticatedAdminEventsIdRoute =
  AuthenticatedAdminEventsIdRouteImport.update({
    id: '/admin/events/$id',
    path: '/admin/events/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRoute
  '/scan': typeof AuthenticatedScanRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/scan/success': typeof AuthenticatedScanSuccessRoute
  '/events/$slug/rsvp': typeof EventsSlugRsvpRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRoute
  '/scan': typeof AuthenticatedScanRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/scan/success': typeof AuthenticatedScanSuccessRoute
  '/events/$slug/rsvp': typeof EventsSlugRsvpRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/api': typeof ApiRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/scan': typeof AuthenticatedScanRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/scan/success': typeof AuthenticatedScanSuccessRoute
  '/events/$slug/rsvp': typeof EventsSlugRsvpRoute
  '/_authenticated/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/login'
    | '/mission'
    | '/privacy'
    | '/terms'
    | '/app'
    | '/scan'
    | '/auth/callback'
    | '/scan/success'
    | '/events/$slug/rsvp'
    | '/admin/events/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/login'
    | '/mission'
    | '/privacy'
    | '/terms'
    | '/app'
    | '/scan'
    | '/auth/callback'
    | '/scan/success'
    | '/events/$slug/rsvp'
    | '/admin/events/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/api'
    | '/login'
    | '/mission'
    | '/privacy'
    | '/terms'
    | '/_authenticated/app'
    | '/_authenticated/scan'
    | '/auth/callback'
    | '/_authenticated/scan/success'
    | '/events/$slug/rsvp'
    | '/_authenticated/admin/events/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiRoute: typeof ApiRoute
  LoginRoute: typeof LoginRoute
  MissionRoute: typeof MissionRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EventsSlugRsvpRoute: typeof EventsSlugRsvpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/events/$slug/rsvp': {
      id: '/events/$slug/rsvp'
      path: '/events/$slug/rsvp'
      fullPath: '/events/$slug/rsvp'
      preLoaderRoute: typeof EventsSlugRsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scan/success': {
      id: '/_authenticated/scan/success'
      path: '/success'
      fullPath: '/scan/success'
      preLoaderRoute: typeof AuthenticatedScanSuccessRouteImport
      parentRoute: typeof AuthenticatedScanRoute
    }
    '/_authenticated/admin/events/$id': {
      id: '/_authenticated/admin/events/$id'
      path: '/admin/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AuthenticatedAdminEventsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedScanRouteChildren {
  AuthenticatedScanSuccessRoute: typeof AuthenticatedScanSuccessRoute
}

const AuthenticatedScanRouteChildren: AuthenticatedScanRouteChildren = {
  AuthenticatedScanSuccessRoute: AuthenticatedScanSuccessRoute,
}

const AuthenticatedScanRouteWithChildren =
  AuthenticatedScanRoute._addFileChildren(AuthenticatedScanRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRouteWithChildren
  AuthenticatedAdminEventsIdRoute: typeof AuthenticatedAdminEventsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedScanRoute: AuthenticatedScanRouteWithChildren,
  AuthenticatedAdminEventsIdRoute: AuthenticatedAdminEventsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiRoute: ApiRoute,
  LoginRoute: LoginRoute,
  MissionRoute: MissionRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EventsSlugRsvpRoute: EventsSlugRsvpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
